const Homeproduct = [
    {
      id: 1,
      Name: "Refrigerator",
      price: "26",
      image: "image/ref1.jpeg",
      cat: "electronics",
      type: "new",
    },
    {
      id: 2,
      Name: "Screen Stand",
      price: "96",
      image: "image/ss3.jpg",
      cat: "screestand",
      type: "new",
    },
    {
      id: 3,
      Name: "Iphone 15",
      price: "300",
      image: "image/iphone15.jpg",
      cat: "phone",
      type: "new",
    },
    {
      id: 4,
      Name: "Anker Prime",
      price: "956",
      image: "image/ankerprime.jpg",
      cat: "electronics",
      type: "featured",
    },
    {
      id: 5,
      Name: "Apple Ipad",
      price: "389",
      image: "image/appleipad.jpg",
      cat: "phone",
      type: "feature",
    },
    {
      id: 6,
      Name: "Multi Adapter",
      price: "67",
      image: "image/multiadapter.jpg",
      cat: "electronics",
      type: "top",
    },
    {
      id: 7,
      Name: "Wireless Charger",
      price: "76",
      image: "image/wirelesscharger.jpg",
      cat: "phone",
      type: "feature",
    },
    {
      id: 8,
      Name: "TCL LED",
      price: "350",
      image: "image/tcl.jpg",
      cat: "tv",
      type: "top",
    },
    {
      id: 9,
      Name: "Yee Light",
      price: "807",
      image: "image/yeelight.jpg",
      cat: "electronics",
      type: "new",
    },
    {
      id: 10,
      Name: "L shape Table",
      price: "807",
      image: "image/gameLshape.jpg",
      cat: "laptop",
      type: "new",
    },
    {
      id: 11,
      Name: "XBOX",
      price: "807",
      image: "image/xbox.jpg",
      cat: "games",
      type: "featured",
    },
    {
      id: 12,
      Name: "Virtual Reality",
      price: "500",
      image: "image/vr.jpg",
      cat: "games",
      type: "new",
    },
    {
      id: 13,
      Name: "Play Station 5",
      price: "1200",
      image: "image/ps5.jpg",
      cat: "games",
      type: "top",
    },
    {
      id: 14,
      Name: "Nine Tendo ",
      price: "400",
      image: "image/nintendo.jpg",
      cat: "games",
      type: "top",
    },
    
  ];
  export default Homeproduct;
  